services:
  pgdatabase:
    image: postgres:16
    container_name: ufc_db_cont
    env_file:
      - .env
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  pgadmin:
    image: dpage/pgadmin4 
    container_name: ufc_pgadmin_cont
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "8085:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - pgdatabase

  app:
    build: . 
    container_name: ufc_runner 
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./plots:/app/plots
    depends_on:
      pgdatabase: 
        condition: service_healthy


volumes: 
  postgres_data:
  pgadmin_data: